{
  "formatVersion": "1.1",
  "component": {
    "group": "com.argon.sdk",
    "module": "mobsdk",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mobsdk-1.0.0.aar",
          "url": "mobsdk-1.0.0.aar",
          "size": 277733,
          "sha512": "025c8ec4ae576df37380fd21e6cc71fb5a18771613197c46fb61cf2fd5fd69c8a30fa5237f339d4295d02c9428b0e9589d0dca00fd046f16e80a963037919fcd",
          "sha256": "a353ccf4248a4866a1d63e3d6a0e2802cce8c43472aae107f094afb45fa0f537",
          "sha1": "aad2f9b01dfb2e6a0a2d86d4b71c2190161e4cc6",
          "md5": "ec21f3eec1f70af04d7f7297197812f9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.percentlayout",
          "module": "percentlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0-alpha02"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus",
          "version": {
            "requires": "11.9.0.1"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tp_exchange",
          "version": {
            "requires": "40.11.9.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-crosspromotion",
          "version": {
            "requires": "27.11.9.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "com.applovin.mediation",
          "module": "google-adapter",
          "version": {
            "requires": "23.0.0.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "google-adapter",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.applovin.mediation",
          "module": "google-ad-manager-adapter",
          "version": {
            "requires": "23.0.0.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "google-ad-manager-adapter",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-googlex",
          "version": {
            "requires": "2.11.9.0.1"
          }
        },
        {
          "group": "com.facebook.android",
          "module": "audience-network-sdk",
          "version": {
            "requires": "6.17.0"
          }
        },
        {
          "group": "com.applovin.mediation",
          "module": "facebook-adapter",
          "version": {
            "requires": "6.17.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "facebook-adapter",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-facebook",
          "version": {
            "requires": "1.11.9.0.1"
          }
        },
        {
          "group": "com.google.ads.mediation",
          "module": "facebook",
          "version": {
            "requires": "6.17.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "facebook",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "requires": "12.5.0"
          }
        },
        {
          "group": "com.google.ads.mediation",
          "module": "applovin",
          "version": {
            "requires": "12.5.0.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "applovin",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-applovin",
          "version": {
            "requires": "9.11.9.0.1"
          }
        },
        {
          "group": "com.pangle.global",
          "module": "ads-sdk",
          "version": {
            "requires": "5.9.0.6"
          }
        },
        {
          "group": "com.applovin.mediation",
          "module": "bytedance-adapter",
          "version": {
            "requires": "5.9.0.6.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "bytedance-adapter",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-pangle",
          "version": {
            "requires": "19.11.9.0.1"
          }
        },
        {
          "group": "com.google.ads.mediation",
          "module": "pangle",
          "version": {
            "requires": "5.9.0.6.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "pangle",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.unity3d.ads",
          "module": "unity-ads",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.applovin.mediation",
          "module": "unityads-adapter",
          "version": {
            "requires": "4.12.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "unityads-adapter",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-unity",
          "version": {
            "requires": "5.11.9.0.1"
          }
        },
        {
          "group": "com.google.ads.mediation",
          "module": "unity",
          "version": {
            "requires": "4.12.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "unity",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.vungle",
          "module": "vungle-ads",
          "version": {
            "requires": "7.3.2"
          }
        },
        {
          "group": "com.applovin.mediation",
          "module": "vungle-adapter",
          "version": {
            "requires": "7.3.2.2"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-vunglex",
          "version": {
            "requires": "7.11.9.0.1"
          }
        },
        {
          "group": "com.google.ads.mediation",
          "module": "vungle",
          "version": {
            "requires": "7.3.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "vungle",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.ironsource.sdk",
          "module": "mediationsdk",
          "version": {
            "requires": "8.1.0"
          }
        },
        {
          "group": "com.applovin.mediation",
          "module": "ironsource-adapter",
          "version": {
            "requires": "8.1.0.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "ironsource-adapter",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-ironsource",
          "version": {
            "requires": "10.11.9.0.1"
          }
        },
        {
          "group": "com.google.ads.mediation",
          "module": "ironsource",
          "version": {
            "requires": "8.1.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "ironsource",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "videojs",
          "version": {
            "requires": "16.7.61"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "mbjscommon",
          "version": {
            "requires": "16.7.61"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "playercommon",
          "version": {
            "requires": "16.7.61"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "reward",
          "version": {
            "requires": "16.7.61"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "videocommon",
          "version": {
            "requires": "16.7.61"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "same",
          "version": {
            "requires": "16.7.61"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "interstitialvideo",
          "version": {
            "requires": "16.7.61"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "interstitial",
          "version": {
            "requires": "16.7.61"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "mbnative",
          "version": {
            "requires": "16.7.61"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "nativeex",
          "version": {
            "requires": "16.7.61"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "mbbanner",
          "version": {
            "requires": "16.7.61"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "mbbid",
          "version": {
            "requires": "16.7.61"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "mbnativeadvanced",
          "version": {
            "requires": "16.7.61"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "mbsplash",
          "version": {
            "requires": "16.7.61"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "newinterstitial",
          "version": {
            "requires": "16.7.61"
          }
        },
        {
          "group": "com.applovin.mediation",
          "module": "mintegral-adapter",
          "version": {
            "requires": "16.7.61.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "mintegral-adapter",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-mintegralx_overseas",
          "version": {
            "requires": "18.11.9.0.1"
          }
        },
        {
          "group": "com.google.ads.mediation",
          "module": "mintegral",
          "version": {
            "requires": "16.7.61.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "mintegral",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.chartboost",
          "module": "chartboost-sdk",
          "version": {
            "requires": "9.7.0"
          }
        },
        {
          "group": "com.chartboost",
          "module": "chartboost-mediation-sdk",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "com.chartboost",
          "module": "chartboost-mediation-adapter-chartboost",
          "version": {
            "requires": "4.9.5.0.0"
          }
        },
        {
          "group": "com.applovin.mediation",
          "module": "chartboost-adapter",
          "version": {
            "requires": "9.7.0.0"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-helium",
          "version": {
            "requires": "30.11.9.0.1"
          }
        },
        {
          "group": "com.google.ads.mediation",
          "module": "chartboost",
          "version": {
            "requires": "9.7.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "chartboost",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.fyber",
          "module": "marketplace-sdk",
          "version": {
            "requires": "8.2.7"
          }
        },
        {
          "group": "com.applovin.mediation",
          "module": "fyber-adapter",
          "version": {
            "requires": "8.2.7.1"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-fyber",
          "version": {
            "requires": "24.11.9.0.1"
          }
        },
        {
          "group": "com.google.ads.mediation",
          "module": "fyber",
          "version": {
            "requires": "8.2.7.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "fyber",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.bigossp",
          "module": "bigo-ads",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "com.bigossp",
          "module": "max-mediation",
          "version": {
            "requires": "4.8.0.0"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-bigo",
          "version": {
            "requires": "57.11.9.0.1"
          }
        },
        {
          "group": "com.bigossp",
          "module": "admob-mediation",
          "version": {
            "requires": "4.8.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "admob-mediation",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.yandex.android",
          "module": "mobileads",
          "version": {
            "requires": "7.1.0"
          }
        },
        {
          "group": "com.applovin.mediation",
          "module": "yandex-adapter",
          "version": {
            "requires": "7.1.0.0"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-yandex",
          "version": {
            "requires": "50.11.9.0.1"
          }
        },
        {
          "group": "com.my.target",
          "module": "mytarget-sdk",
          "version": {
            "requires": "5.21.0"
          }
        },
        {
          "group": "com.applovin.mediation",
          "module": "mytarget-adapter",
          "version": {
            "requires": "5.21.0.0"
          }
        },
        {
          "group": "com.tradplusad",
          "module": "tradplus-mytarget",
          "version": {
            "requires": "33.11.9.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "mobsdk-1.0.0.aar",
          "url": "mobsdk-1.0.0.aar",
          "size": 277733,
          "sha512": "025c8ec4ae576df37380fd21e6cc71fb5a18771613197c46fb61cf2fd5fd69c8a30fa5237f339d4295d02c9428b0e9589d0dca00fd046f16e80a963037919fcd",
          "sha256": "a353ccf4248a4866a1d63e3d6a0e2802cce8c43472aae107f094afb45fa0f537",
          "sha1": "aad2f9b01dfb2e6a0a2d86d4b71c2190161e4cc6",
          "md5": "ec21f3eec1f70af04d7f7297197812f9"
        }
      ]
    }
  ]
}
